### ISSUE TITLE
Command line option to enable sphinx extensions

### ISSUE THREAD

**Issue by languitar** [twolfson/restructuredtext-lint#17]
It would be nice if there was a command line option for the cli program to enable the sphinx extensions.

**Comment by twolfson** [comment]
This has been explored in #14.

https://github.com/twolfson/restructuredtext-lint/pull/14

While we can support some of the Sphinx extensions, it's impossible to support all of them due to Sphinx using a different parser than generic `docutils`. Instead, we should look at using another tool to specifically lint Sphinx-specific rst that uses that parser.

**Comment by languitar** [comment]
Thanks for the information.
