### ISSUE TITLE
pre-commit integration

### ISSUE THREAD

**Issue by grintor** [twolfson/restructuredtext-lint#60]
This repo is a great plugin for [pre-commit](https://pre-commit.com/)

In fact, I first learned about it by looking at the github repo for pylint, which is already using it as a pre-commit hook [here](https://github.com/pytest-dev/pytest/blob/31f9e5bcdd3396ac0daf6d35c9d8aa8a2cd72993/.pre-commit-config.yaml#L79)

Let's make it official and publish a .pre-commit-hooks.yaml file here to make it a native plugin.

**Comment by twolfson** [comment]
Hey @grintor, thanks for writing in! =)

Unfortunately, I fundamentally disagree with the architectural approach `pre-commit` has gone with and choose not to support it as part of my repo =/

You can read the discussion on previous issues: https://github.com/twolfson/restructuredtext-lint/pull/51 (primary), https://github.com/twolfson/restructuredtext-lint/issues/50 (secondary)

I implore you to take your positive motivation and encourage `pre-commit` to go the route of a centralized repository instead of burdening maintainers =)
